<?php // generated by https://www.devsense.com/

/**
 * Returns the number of rows in the result set.
 *
 * @param mysqli_result $result Procedural style only: A mysqli_result object returned by mysqli_query(), mysqli_store_result(), mysqli_use_result() or mysqli_stmt_get_result().
 * @return int|string An `int` representing the number of fetched rows. Returns `0` in unbuffered mode unless all rows have been fetched from the server.
 */
function mysqli_num_rows($result): int|string { /* function body is hidden */ }