<?php // generated by https://www.devsense.com/

/**
 * The include statement includes and evaluates the specified file.
 *
 * @param string $path
 */
function include($path): mixed { /* function body is hidden */ }