<?php // generated by https://www.devsense.com/

/**
 * Output one or more strings
 * Outputs one or more expressions, with no additional newlines or spaces.
 *
 * @param string $expressions One or more string expressions to output, separated by commas. Non-string values will be coerced to strings, even when the `strict_types` directive is enabled.
 * @return void
 */
function echo(...$expressions): void { /* function body is hidden */ }