<?php // generated by https://www.devsense.com/

/**
 * Destroys all data registered to a session
 * session_destroy() destroys all of the data associated with the current session. It does not unset any of the global variables associated with the session, or unset the session cookie. To use the session variables again, session_start() has to be called.
 * @return bool Returns `true` on success or `false` on failure.
 */
function session_destroy(): bool { /* function body is hidden */ }