<?php // generated by https://www.devsense.com/

/**
 * Equivalent to `exit`
 * This language construct is equivalent to exit().
 *
 * @param int|null $status If `status` is a string, this function prints the `status` just before exiting. If `status` is an `int`, that value will be used as the exit status and not printed. Exit statuses should be in the range 0 to 254, the exit status 255 is reserved by PHP and shall not be used. The status 0 is used to terminate the program successfully.
 * @return void
 */
function die($status): void { /* function body is hidden */ }