<?php // generated by https://www.devsense.com/

/**
 * Calculates the MD5 hash of `string` using the » RSA Data Security, Inc. MD5 Message-Digest Algorithm , and returns that hash.
 *
 * @param string $string The string.
 * @param bool|null $binary If the optional `binary` is set to `true` , then the md5 digest is instead returned in raw binary format with a length of 16.
 * @return string Returns the hash as a 32-character hexadecimal number.
 */
function md5($string, $binary = false): string { /* function body is hidden */ }