<?php // generated by https://www.devsense.com/

/**
 * Determine if a variable is considered set, this means if a variable is declared and is different than `null` .
 *
 * @param mixed $var The variable to be checked.
 * @param mixed $vars Further variables.
 * @return bool Returns `true` if `var` exists and has any value other than `null` . `false` otherwise.
 */
function isset($var, ...$vars): bool { /* function body is hidden */ }