<?php // generated by https://www.devsense.com/

/**
 * Fetch the next row of a result set as an associative, a numeric array, or both
 * Fetches one row of data from the result set and returns it as an array. Each subsequent call to this function will return the next row within the result set, or `null` if there are no more rows.
 *
 * @param mysqli_result $result Procedural style only: A mysqli_result object returned by mysqli_query(), mysqli_store_result(), mysqli_use_result() or mysqli_stmt_get_result().
 * @param int|null $mode This optional parameter is a constant indicating what type of array should be produced from the current row data. The possible values for this parameter are the constants `MYSQLI_ASSOC` , `MYSQLI_NUM` , or `MYSQLI_BOTH` . By using the `MYSQLI_ASSOC` constant this function will behave identically to the mysqli_fetch_assoc(), while `MYSQLI_NUM` will behave identically to the mysqli_fetch_row() function. The final option `MYSQLI_BOTH` will create a single array with the attributes of both.
 * @return array|bool|null Returns an array representing the fetched row, `null` if there are no more rows in the result set, or `false` on failure.
 */
function mysqli_fetch_array($result, $mode = MYSQLI_BOTH): array|bool|null { /* function body is hidden */ }