<?php // generated by https://www.devsense.com/

/**
 * The include_once statement includes and evaluates the specified file during the execution of the script. This is a behavior similar to the include statement, with the only difference being that if the code from a file has already been included, it will not be included again. As the name suggests, it will be included just once.
 *
 * include_once may be used in cases where the same file might be included and evaluated more than once during a particular execution of a script, so in this case it may help avoid problems such as function redefinitions, variable value reassignments, etc.
 *
 * @param string $path
 */
function include_once($path): mixed { /* function body is hidden */ }