<?php // generated by https://www.devsense.com/

/**
 * Escapes special characters in a string for use in an SQL statement, taking into account the current charset of the connection
 * This function is used to create a legal SQL string that you can use in an SQL statement. The given string is encoded to produce an escaped SQL string, taking into account the current character set of the connection.
 *
 * @param mysqli $mysql Procedural style only: A mysqli object returned by mysqli_connect() or mysqli_init()
 * @param string $string The string to be escaped. Characters encoded are `NUL (ASCII 0), \n, \r, \, ', ", and
 *                           Control-Z`.
 * @return string Returns an escaped string.
 */
function mysqli_real_escape_string($mysql, $string): string { /* function body is hidden */ }