<?php // generated by https://www.devsense.com/

/**
 * Performs a query on the database
 * Performs a `query` against the database.
 *
 * @param mysqli $mysql Procedural style only: A mysqli object returned by mysqli_connect() or mysqli_init()
 * @param string $query The query string.
 * @param int|null $result_mode The result mode can be one of 3 constants indicating how the result will be returned from the MySQL server. `MYSQLI_STORE_RESULT` (default) - returns a mysqli_result object with buffered result set. `MYSQLI_USE_RESULT` - returns a mysqli_result object with unbuffered result set. As long as there are pending records waiting to be fetched, the connection line will be busy and all subsequent calls will return error `Commands out of sync`. To avoid the error all records must be fetched from the server or the result set must be discarded by calling mysqli_free_result(). `MYSQLI_ASYNC` (available with mysqlnd) - the query is performed asynchronously and no result set is immediately returned. mysqli_poll() is then used to get results from such queries. Used in combination with either `MYSQLI_STORE_RESULT` or `MYSQLI_USE_RESULT` constant.
 * @return bool|mysqli_result Returns `false` on failure. For successful queries which produce a result set, such as `SELECT, SHOW, DESCRIBE` or `EXPLAIN`, mysqli_query() will return a mysqli_result object. For other successful queries, mysqli_query() will return `true` .
 */
function mysqli_query($mysql, $query, $result_mode = MYSQLI_STORE_RESULT): bool|mysqli_result { /* function body is hidden */ }